### PR TITLE
Add support for the Dutch language in the Mi899 application + correction of a minor typo in the menu

### PR DESCRIPTION
**Pull request by DrywFiltiarn**

### CODE REVIEW

**Review by miyconst — APPROVED** [review]
Thank you for the translation and the typo fix! Would you be able to also translate this item?

https://github.com/miyconst/Mi899/pull/112/files#diff-94c5edd101dbbb31712065abecda7c3f3d194991ec7f4e505b2c914c79bb557fR492

**Comment by DrywFiltiarn** [comment]
A translation for the menu item you mean? I can do that. I already tried, but it seems some of the menu-items do not yet use the translation file?

**Comment by miyconst** [comment]
>A translation for the menu item you mean?

No, I meant this line in the JSON file:

```json
"ToolPartialForm.ToolPartialForm.txtReadme.Text": "# BIOS read and write \r\n\r\nOn this form, you can dump your current BIOS to create a backup or flash selected BIOS onto your motherboard.\r\n\r\n## Mi899:\r\n\r\n- Prepares files and scripts to simplify BIOS read/write process.\r\n- Copies the files and the scripts into a temp folder.\r\n- Opens the temp folder location.\r\n- Does NOT read or write your motherboard’s BIOS.\r\n- Does NOT validate the compatibility of your motherboard with the selected BIOS.\r\n- Does NOT validate the BIOS read/write result.\r\n\r\n## Final warning:\r\n\r\nIf something goes wrong, you are the only one responsible for your actions. \r\n\r\n## Usage\r\n\r\n### To dump your current motherboard BIOS:\r\n\r\n- Click the `[Dump current BIOS]` button.\r\n- Wait until Mi899 opens a temp folder with prepared files.\r\n- Run the `dump.bat` script from the folder as administrator.\r\n\r\n### To flash a BIOS onto your motherboard:\r\n\r\n- Select the desired BIOS in the `BIOS` drop-down list located on the left side of the form.\r\n- Click the `[Flash selected BIOS]` button.\r\n- Wait until Mi899 opens a temp folder with prepared files.\r\n- Run the `flash.bat` script from the folder as administrator."
```

**Comment by DrywFiltiarn** [comment]
I see, will get it done tomorrow and create an additional PR for it.

**Pull request merged**
