### PR TITLE
Create README.TR.md

### PR DESCRIPTION
**Pull request by fastengineer**

### CODE REVIEW

**Comment by miyconst** [comment]
@fastengineer thank you very much for another translation. It's Turkish, right?

Could you please also translate the application titles, it can be found in these file - [`src/Mi899.Data/I18n.json`](https://github.com/miyconst/Mi899/blob/master/src/Mi899.Data/I18n.json#L2)?

**Comment by miyconst** [comment]
@chandrey206 why did you close this pull request?

**Comment by fastengineer** [comment]
"AboutPartialForm.lblAuthorCaption.Text": "Yazar:",
    "AboutPartialForm.lblToolSet.Text": "X99 Araç Seti",
    "AboutPartialForm.lblVersionCaption.Text": "Versiyon:",
    "BiosesPartialForm.btnSearch.Text": "Uygula",
    "BiosesPartialForm.grdBioses.colChipsets.HeaderText": "Chipsetler",
    "BiosesPartialForm.grdBioses.colDescription.HeaderText": "Açıklama",
    "BiosesPartialForm.grdBioses.colFileName.HeaderText": "Dosya yolu",
    "BiosesPartialForm.grdBioses.colName.HeaderText": "Ad",
    "BiosesPartialForm.grdBioses.colProperties.HeaderText": "Özellikler",
    "BiosesPartialForm.grdBioses.colTags.HeaderText": "Etiketler",
    "BiosesPartialForm.lblSearch.Text": "Ara:",
    "MainForm.msiExit.Text": "Çık",
    "MainForm.msiExplore.Text": "Gezin",
    "MainForm.msiExploreBioses.Text": "BIOS",
    "MainForm.msiExploreMotherboards.Text": "Anakartlar",
    "MainForm.msiFile.Text": "Dosya",
    "MainForm.msiFileReadMe.Text": "Beni oku!",
    "MainForm.msiHelp.Text": "Yardım",
    "MainForm.msiHelpAbout.Text": "Hakkında...",
    "MainForm.msiHelpHowTo.Text": "Nasıl yapılır",
    "MainForm.msiHelpHowToRamTimings.Text": "RAM zamanlamalarını ayarla",
    "MainForm.msiHelpHowToTurboUnlock.Text": "Turbo Boost kilidini aç",
    "MainForm.msiHelpHowToUseCh341a.Text": "CH341A BIOS Programlayıcısı nasıl kullanılır?",
    "MainForm.Text": "Mi899 - X99 Araç Seti",
    "MainForm.tsslVersion.Text": "Mi899 Versiyon 1.0.1 - Tüm hakları saklıdır © Miyconst",
    "MotherboardPartialForm.grdBioses.colChipsets.HeaderText": "Chipsetler",
    "MotherboardPartialForm.grdBioses.colId.HeaderText": "No",
    "MotherboardPartialForm.grdBioses.colName.HeaderText": "Ad",
    "MotherboardPartialForm.grdBioses.colPath.HeaderText": "Yol",
    "MotherboardPartialForm.grdBioses.colProperties.HeaderText": "Özellikler",
    "MotherboardPartialForm.grdImages.colImage.HeaderText": "Resim",
    "MotherboardPartialForm.grdImages.colPath.HeaderText": "Yol",
    "MotherboardPartialForm.grdLinks.colAuthor.HeaderText": "Yazar",
    "MotherboardPartialForm.grdLinks.colName.HeaderText": "Ad",
    "MotherboardPartialForm.grdLinks.colUrl.HeaderText": "Link",
    "MotherboardPartialForm.lblBrand.Text": "Marka:",
    "MotherboardPartialForm.lblDescription.Text": "Açıklama:",
    "MotherboardPartialForm.lblId.Text": "No:",
    "MotherboardPartialForm.lblModel.Text": "Model:",
    "MotherboardPartialForm.lblName.Text": "Ad:",
    "MotherboardPartialForm.lblTags.Text": "Etiketler:",
    "MotherboardPartialForm.lblTools.Text": "Araçlar:",
    "MotherboardPartialForm.lblVersion.Text": "Versiyon:",
    "MotherboardPartialForm.tpBioses.Text": "BIOS",
    "MotherboardPartialForm.tpImages.Text": "Görüntüler",
    "MotherboardPartialForm.tpInfo.Text": "Açıklama",
    "MotherboardPartialForm.tpLinks.Text": "Linkler",
    "MotherboardsPartialForm.btnSearch.Text": "Uygula",
    "MotherboardsPartialForm.grdMotherboards.colDescription.HeaderText": "Açıklama",
    "MotherboardsPartialForm.grdMotherboards.colImage.HeaderText": "Resim",
    "MotherboardsPartialForm.grdMotherboards.colName.HeaderText": "Ad",
    "MotherboardsPartialForm.grdMotherboards.colSelect.Text": "Seç",
    "MotherboardsPartialForm.grdMotherboards.colTags.HeaderText": "Etiketler",
    "MotherboardsPartialForm.grdMotherboards.colVersion.HeaderText": "Versiyon",
    "MotherboardsPartialForm.lblSearch.Text": "Ara:",
    "ReadMePartialForm.wbReadme.DocumentText": "Benioku.md",
    "ToolPartialForm.btnDump.Text": "Şu anki BIOS'u al",
    "ToolPartialForm.btnFlash.Text": "Seçili BIOS'u flashla",
    "ToolPartialForm.cbExecuteScript.Text": "Scripti çalıştır",
    "ToolPartialForm.lblBios.Text": "BIOS:",
    "ToolPartialForm.lblMotherboard.Text": "Anakart:",
    "ToolPartialForm.lblTool.Text": "Araç:",

**Comment by fastengineer** [comment]
I couldn't read the last sentence. Can you share it here?

**Comment by miyconst** [comment]
@fastengineer here is the last section to translate:

------------

# BIOS read and write

On this form, you can dump your current BIOS to create a backup or flash selected BIOS onto your motherboard.

## Mi899:

- Prepares files and scripts to simplify BIOS read/write process. 
- Copies the files and the scripts into a temp folder. 
- Opens the temp folder location. 
- Does NOT read or write your motherboard’s BIOS. 
- Does NOT validate the compatibility of your motherboard with the selected BIOS. 
- Does NOT validate the BIOS read/write the result. 

## Final warning:

If something goes wrong, you are the only one responsible for your actions.

## Usage

### To dump your current motherboard BIOS:

- Click the [Dump current BIOS] button. 
- Wait until Mi899 opens a temp folder with prepared files. 
- Run the `dump.bat` script from the folder as administrator. 

### To flash a BIOS onto your motherboard:

- Select the desired BIOS in the BIOS drop-down list located on the left side of the form. 
- Click the [Flash selected BIOS] button. 
- Wait until Mi899 opens a temp folder with prepared files. 
- Run the `flash.bat` script from the folder as administrator.

**Comment by fastengineer** [comment]
Readme file already translated on PR.

**Comment by miyconst** [comment]
@fastengineer these are two different `README`s used on two different pages.

**Pull request closed without merging**
